version: 3
services:
  postgres:
    image: 'postgres:latest'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=4system
      - APP_DB_PASS=4system
      - APP_DB_NAME=4system
    ports:
      - '5432:5432'
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d/
  backend:
    build: ./backend/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - frontend
  frontend:
    build: ./frontend/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
      - postgres
